// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DataCtrlEntry(	// src/main/scala/dongjiang/data/DataCM.scala:64:7
  input         clock,	// src/main/scala/dongjiang/data/DataCM.scala:64:7
                reset,	// src/main/scala/dongjiang/data/DataCM.scala:64:7
  input  [2:0]  io_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_cutHnTxnID_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_cutHnTxnID_bits_before,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_cutHnTxnID_bits_next,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_alloc_ready,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_alloc_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_alloc_bits_hnTxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_alloc_bits_dataVec_0,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_alloc_bits_dataVec_1,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_task_bits_hnTxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_task_bits_dataOp_repl,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_dataOp_read,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_dataOp_send,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_dataOp_save,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_ds_bank,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_task_bits_ds_idx,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_task_bits_dataVec_0,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_dataVec_1,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [15:0] io_task_bits_txDat_DBID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [2:0]  io_task_bits_txDat_CBusy,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [7:0]  io_task_bits_txDat_DataSource,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [2:0]  io_task_bits_txDat_Resp,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [1:0]  io_task_bits_txDat_RespErr,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_task_bits_txDat_Opcode,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [7:0]  io_task_bits_txDat_HomeNID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [11:0] io_task_bits_txDat_TxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [7:0]  io_task_bits_txDat_SrcID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_task_bits_txDat_TgtID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_task_bits_txDat_QoS,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_resp_ready,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_resp_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_resp_bits_hnTxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_clean_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [3:0]  io_clean_bits_hnTxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_clean_bits_dataVec_0,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_clean_bits_dataVec_1,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readForRepl,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_readToDB_ready,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToDB_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToDB_bits_ds_bank,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_readToDB_bits_ds_idx,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [2:0]  io_readToDB_bits_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToDB_bits_beatNum,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToDB_bits_critical,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_readToDS_ready,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToDS_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToDS_bits_ds_bank,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_readToDS_bits_ds_idx,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [2:0]  io_readToDS_bits_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToDS_bits_beatNum,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToDS_bits_critical,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToDS_bits_repl,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_readToCHI_ready,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToCHI_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [2:0]  io_readToCHI_bits_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_readToCHI_bits_beatNum,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_readToCHI_bits_critical,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_dsWriDB_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [2:0]  io_dsWriDB_bits_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input         io_txDatFire_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  input  [2:0]  io_txDatFire_bits_dcid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [1:0]  io_txDatBits_DataID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [15:0] io_txDatBits_DBID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [2:0]  io_txDatBits_CBusy,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [7:0]  io_txDatBits_DataSource,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [2:0]  io_txDatBits_Resp,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [1:0]  io_txDatBits_RespErr,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_txDatBits_Opcode,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [7:0]  io_txDatBits_HomeNID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [11:0] io_txDatBits_TxnID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [7:0]  io_txDatBits_SrcID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
                io_txDatBits_TgtID,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_txDatBits_QoS,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output        io_state_valid,	// src/main/scala/dongjiang/data/DataCM.scala:68:14
  output [3:0]  io_state_bits_hnTxnID	// src/main/scala/dongjiang/data/DataCM.scala:68:14
);

  reg  [3:0]      reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_task_dataOp_send;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_task_dataOp_save;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_task_ds_bank;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [3:0]      reg_task_ds_idx;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_task_dataVec_0;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_task_dataVec_1;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [15:0]     reg_task_txDat_DBID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [2:0]      reg_task_txDat_CBusy;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [7:0]      reg_task_txDat_DataSource;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [2:0]      reg_task_txDat_Resp;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [1:0]      reg_task_txDat_RespErr;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [3:0]      reg_task_txDat_Opcode;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [7:0]      reg_task_txDat_HomeNID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [11:0]     reg_task_txDat_TxnID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [7:0]      reg_task_txDat_SrcID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [7:0]      reg_task_txDat_TgtID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [3:0]      reg_task_txDat_QoS;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [2:0]      reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_opBeat;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [1:0]      reg_wRBeat;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg  [1:0]      reg_wSBeat;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_dataVec_0;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  reg             reg_dataVec_1;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
  wire [1:0]      _next_opBeat_T = {reg_task_dataVec_1, reg_task_dataVec_0};	// src/main/scala/dongjiang/bundle/DJBundles.scala:139:29, src/main/scala/dongjiang/data/DataCM.scala:92:20
  wire            _GEN = (&_next_opBeat_T) ? reg_wSBeat != 2'h2 : reg_task_dataVec_1;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/bundle/DJBundles.scala:139:{29,36}, src/main/scala/dongjiang/data/DataCM.scala:92:20, :104:43
  wire            io_readForRepl_0 = reg_state == 3'h2;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:53:25, :92:20
  wire            _io_readToDB_valid_T_1 = reg_state == 3'h3;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:54:25, :92:20
  wire            io_readToDB_valid_0 = io_readForRepl_0 | _io_readToDB_valid_T_1;	// src/main/scala/dongjiang/data/DataCM.scala:53:25, :54:25, :121:45
  wire            _io_readToDS_valid_T_1 = reg_state == 3'h5;	// src/main/scala/dongjiang/data/DataCM.scala:56:25, :92:20
  wire            io_readToDS_valid_0 = io_readForRepl_0 | _io_readToDS_valid_T_1 & ~(|reg_wRBeat);	// src/main/scala/dongjiang/data/DataCM.scala:46:33, :53:25, :56:25, :92:20, :128:{45,59}
  wire            _io_readToCHI_valid_T = reg_state == 3'h4;	// src/main/scala/dongjiang/data/DataCM.scala:55:25, :92:20
  wire            io_readToCHI_valid_0 = _io_readToCHI_valid_T & ~(|reg_wRBeat);	// src/main/scala/dongjiang/data/DataCM.scala:46:33, :55:25, :92:20, :136:45
  wire            _GEN_0 = io_readToDB_ready & io_readToDB_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:121:45
  wire            _GEN_1 = io_readToDS_ready & io_readToDS_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:128:45
  wire            _io_resp_valid_T = reg_state == 3'h6;	// src/main/scala/dongjiang/data/DataCM.scala:57:25, :92:20
  wire            io_resp_valid_0 = _io_resp_valid_T & ~(|reg_wRBeat) & ~(|reg_wSBeat);	// src/main/scala/dongjiang/data/DataCM.scala:46:33, :48:33, :57:25, :92:20, :148:59
  wire            taskHit = (|reg_state) & io_task_valid & io_task_bits_hnTxnID == reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :155:{45,68}
  wire            cleanHit = (|reg_state) & io_clean_valid & io_clean_bits_hnTxnID == reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :164:{47,71}
  wire            _set_T = ~(|reg_state) & io_alloc_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20
  wire            dsWriDBHit = (|reg_state) & io_dsWriDB_valid & io_dsWriDB_bits_dcid == io_dcid;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :175:{52,75}
  wire            txDatHit = (|reg_state) & io_txDatFire_valid & io_txDatFire_bits_dcid == io_dcid;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :188:{54,79}
  wire            _GEN_2 = io_readToCHI_ready & io_readToCHI_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:136:45
  wire            _GEN_3 = _GEN_0 | _GEN_1 | _GEN_2;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:203:50
  wire            _GEN_4 = _GEN_3 ? 1'(reg_opBeat + (&_next_opBeat_T)) : reg_opBeat;	// src/main/scala/dongjiang/bundle/DJBundles.scala:139:{29,36}, src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :203:{50,71}, :204:{19,33}
  wire            next_opBeat = ~_set_T & _GEN_4;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:96:22, :201:23, :202:19, :203:71, :204:19
  wire            cutIdHit = (|reg_state) & io_cutHnTxnID_valid & io_cutHnTxnID_bits_before == reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :212:{52,80}
  wire [2:0]      _GEN_5 = _set_T ? 3'h1 : reg_state;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :223:27, :224:20
  wire [2:0]      _next_state_T_1 = io_task_bits_dataOp_read ? 3'h3 : {2'h2, ~io_task_bits_dataOp_send};	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:104:43
  wire [2:0]      _next_state_T_2 = io_task_bits_dataOp_repl ? 3'h2 : _next_state_T_1;	// src/main/scala/chisel3/util/Mux.scala:50:70
  wire [2:0]      _GEN_6 = cleanHit ? 3'h7 : reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:58:25, :92:20, :96:22, :164:47, :235:28, :236:20
  wire [2:0]      _GEN_7 = taskHit ? _next_state_T_2 : _GEN_6;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:96:22, :155:45, :228:21, :229:20, :235:28, :236:20
  wire            _GEN_8 = reg_opBeat ^ _next_opBeat_T != 2'h3;	// src/main/scala/dongjiang/bundle/DJBundles.scala:139:{29,36}, src/main/scala/dongjiang/data/DataCM.scala:54:25, :92:20, :94:25
  wire            _GEN_9 = _GEN_0 & _GEN_8;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:94:25, :240:29
  wire [2:0]      _GEN_10 = _GEN_9 ? 3'h4 : reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:55:25, :92:20, :96:22, :240:{29,46}, :241:20
  wire [2:0]      _next_state_T_3 = reg_task_dataOp_save ? 3'h5 : 3'h6;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:56:25, :57:25, :92:20
  wire [2:0]      _next_state_T_4 = reg_task_dataOp_send ? 3'h4 : _next_state_T_3;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:55:25, :92:20
  wire [2:0]      _GEN_11 = _GEN_9 ? _next_state_T_4 : reg_state;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :240:29, :245:46, :246:20
  wire [2:0]      _next_state_T_5 = reg_task_dataOp_save ? 3'h5 : 3'h6;	// src/main/scala/dongjiang/data/DataCM.scala:56:25, :57:25, :92:20, :255:26
  wire [2:0]      _GEN_12 = _GEN_2 & _GEN_8 ? _next_state_T_5 : reg_state;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:92:20, :94:25, :96:22, :254:{30,47}, :255:{20,26}
  wire [2:0]      _GEN_13 = _GEN_1 & _GEN_8 ? 3'h6 : reg_state;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:57:25, :92:20, :94:25, :96:22, :259:{29,46}, :260:20
  wire [2:0]      _GEN_14 = io_resp_ready & io_resp_valid_0 ? 3'h1 : reg_state;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :148:59, :224:20, :264:26, :265:20
  wire [7:0][2:0] _GEN_15 =
    {{{2'h0, |(2'({1'h0, reg_dataVec_0} + {1'h0, reg_dataVec_1}))}},
     {_GEN_14},
     {_GEN_13},
     {_GEN_12},
     {_GEN_11},
     {_GEN_10},
     {_GEN_7},
     {_GEN_5}};	// <stdin>:952696:5, :952698:5, :953235:5, :953237:5, :953774:5, :953776:5, :954313:5, :954315:5, :954852:5, :954854:5, :955391:5, :955393:5, :955930:5, :955932:5, :956469:5, :956471:5, src/main/scala/dongjiang/bundle/DJBundles.scala:138:{29,39}, src/main/scala/dongjiang/data/DataCM.scala:52:25, :58:25, :92:20, :96:22, :221:21, :223:27, :224:20, :228:21, :229:20, :235:28, :240:46, :241:20, :245:46, :246:20, :254:47, :255:20, :259:46, :260:20, :264:26, :265:20, :269:20, :270:20
  wire [2:0]      next_state = _GEN_15[reg_state];	// src/main/scala/dongjiang/data/DataCM.scala:52:25, :58:25, :92:20, :96:22, :221:21, :223:27, :228:21, :240:46, :245:46, :254:47, :259:46, :264:26, :269:20
  wire            set = _set_T | (|reg_state);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :283:27
  reg  [22:0]     to_cnt;	// src/main/scala/dongjiang/data/DataCM.scala:289:23
  `ifndef SYNTHESIS	// src/main/scala/dongjiang/data/DataCM.scala:143:17
    wire _GEN_16 = reg_state == 3'h1;	// src/main/scala/dongjiang/data/DataCM.scala:52:25, :92:20, :224:20
    wire _GEN_17 = taskHit & ~reset;	// src/main/scala/dongjiang/data/DataCM.scala:143:17, :155:45, :158:12
    wire _GEN_18 = ~_set_T & cleanHit & ~reset;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:143:17, :164:47, :165:23, :169:12
    wire _GEN_19 = ~_set_T & taskHit & ~reset;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:143:17, :155:45, :165:23, :180:12
    wire _GEN_20 = ~_set_T & ~taskHit;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:155:45, :165:23, :178:23
    wire _GEN_21 = _GEN_20 & dsWriDBHit & ~reset;	// src/main/scala/dongjiang/data/DataCM.scala:143:17, :175:52, :178:23, :183:12
    wire _GEN_22 = _GEN_20 & txDatHit & ~reset;	// src/main/scala/dongjiang/data/DataCM.scala:143:17, :178:23, :188:54, :196:12
    wire _GEN_23 = next_state == reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :205:{19,52}, :221:21, :223:27
    wire _GEN_24 = ~_set_T & _GEN_3 & ~reset;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:143:17, :165:23, :203:50, :205:19
    wire _GEN_25 = next_state >= reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :221:21, :223:27, :274:58
    wire _GEN_26 = next_state == 3'h0;	// <stdin>:952701:30, :953240:30, :953779:30, :954318:30, :954857:30, :955396:30, :955935:30, :956474:30, src/main/scala/dongjiang/data/DataCM.scala:50:25, :221:21, :223:27
    wire _GEN_27 = next_state == 3'h1;	// src/main/scala/dongjiang/data/DataCM.scala:52:25, :221:21, :223:27, :224:20
    always @(posedge clock) begin	// src/main/scala/dongjiang/data/DataCM.scala:143:17
      if (~reset & ~(~io_readForRepl_0 | _GEN_0 ^ ~_GEN_1)) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:53:25, :143:{17,18}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:143:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:143:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:143:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:143:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:143:17
      end
      if (_GEN_17 & ~_GEN_16) begin	// src/main/scala/dongjiang/data/DataCM.scala:52:25, :158:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:158:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:158:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:158:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:158:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:158:12
      end
      if (_GEN_17
          & ~(io_task_bits_dataOp_repl | io_task_bits_dataOp_read | io_task_bits_dataOp_send
              | io_task_bits_dataOp_save)) begin	// src/main/scala/dongjiang/data/Bundle.scala:25:41, src/main/scala/dongjiang/data/DataCM.scala:158:12, :159:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:159:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:159:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:159:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:159:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:159:12
      end
      if (_GEN_17 & ~(~io_task_bits_dataVec_0 | reg_dataVec_0)) begin	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :158:12, :160:77
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:160:77
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:160:77: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:160:77
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:160:77
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:160:77
      end
      if (_GEN_17 & ~(~io_task_bits_dataVec_1 | reg_dataVec_1)) begin	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :158:12, :160:77
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:160:77
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:160:77: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:160:77
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:160:77
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:160:77
      end
      if (_GEN_18 & 2'({1'h0, io_clean_bits_dataVec_0} + {1'h0, io_clean_bits_dataVec_1}) == 2'h0) begin	// <stdin>:952696:5, :952698:5, :953235:5, :953237:5, :953774:5, :953776:5, :954313:5, :954315:5, :954852:5, :954854:5, :955391:5, :955393:5, :955930:5, :955932:5, :956469:5, :956471:5, src/main/scala/dongjiang/bundle/DJBundles.scala:138:{29,39}, src/main/scala/dongjiang/data/DataCM.scala:169:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:169:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:169:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:169:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:169:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:169:12
      end
      if (_GEN_18 & ~_GEN_16) begin	// src/main/scala/dongjiang/data/DataCM.scala:52:25, :158:12, :169:12, :170:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:170:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:170:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:170:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:170:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:170:12
      end
      if (_GEN_18 & taskHit) begin	// src/main/scala/dongjiang/data/DataCM.scala:155:45, :169:12, :171:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:171:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:171:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:171:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:171:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:171:12
      end
      if (_GEN_19 & (|reg_wRBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:46:33, :92:20, :180:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:180:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:180:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:180:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:180:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:180:12
      end
      if (_GEN_21 & reg_wRBeat == 2'h0) begin	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20, :183:{12,24}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:183:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:183:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:183:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:183:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:183:12
      end
      if (_GEN_21 & ~(_io_readToDB_valid_T_1 | io_readForRepl_0 | ~reg_opBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:53:25, :54:25, :92:20, :93:33, :183:12, :184:19
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:184:19
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:184:19: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:184:19
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:184:19
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:184:19
      end
      if (_GEN_19 & (|reg_wSBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:48:33, :92:20, :180:12, :193:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:193:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:193:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:193:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:193:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:193:12
      end
      if (_GEN_22 & reg_wSBeat == 2'h0) begin	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20, :196:{12,24}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:196:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:196:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:196:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:196:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:196:12
      end
      if (_GEN_22 & ~(_io_readToCHI_valid_T | _io_readToDS_valid_T_1 | (&reg_state) | _io_resp_valid_T)) begin	// src/main/scala/dongjiang/data/DataCM.scala:55:25, :56:25, :57:25, :58:25, :92:20, :196:12, :197:{12,51}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:197:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:197:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:197:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:197:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:197:12
      end
      if (_GEN_24 & ~(_GEN_23 | ~next_opBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:201:23, :202:19, :203:71, :205:{19,32,52}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:205:19
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:205:19: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:205:19
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:205:19
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:205:19
      end
      if (_GEN_24 & ~(~_GEN_23 | next_opBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:201:23, :202:19, :203:71, :205:{19,52}, :206:19
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:206:19
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:206:19: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:206:19
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:206:19
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:206:19
      end
      if (~reset & ~(~taskHit | ~reg_opBeat)) begin	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :93:33, :143:17, :155:45, :209:17
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:209:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:209:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:209:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:209:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:209:17
      end
      if (~_set_T & cutIdHit & ~reset & ~_GEN_16) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/dongjiang/data/DataCM.scala:52:25, :143:17, :158:12, :165:23, :212:52, :217:12
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:217:12
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:217:12: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:217:12
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:217:12
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:217:12
      end
      if (~reset & ~(_GEN_25 | _io_resp_valid_T | (&reg_state))) begin	// src/main/scala/dongjiang/data/DataCM.scala:57:25, :58:25, :92:20, :143:17, :274:{17,58}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:274:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:274:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:274:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:274:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:274:17
      end
      if (~reset & ~(_GEN_25 | _GEN_26 | _GEN_27)) begin	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :52:25, :143:17, :274:58, :275:17
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:275:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:275:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:275:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:275:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:275:17
      end
      if (~reset & ~(~_GEN_26 | ~(|reg_state) | (&reg_state))) begin	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :58:25, :92:20, :143:17, :276:17
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:276:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:276:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:276:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:276:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:276:17
      end
      if (~reset & ~(~_GEN_27 | ~(|reg_state) | _GEN_16 | _io_resp_valid_T | (&reg_state))) begin	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :52:25, :57:25, :58:25, :92:20, :143:17, :277:17
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:277:17
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:277:17: \n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n");	// src/main/scala/dongjiang/data/DataCM.scala:277:17
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:277:17
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:277:17
      end
      if (~reset & to_cnt > 23'hEA5F) begin	// src/main/scala/dongjiang/data/DataCM.scala:143:17, :289:23
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:289:23
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:289:23: TIMEOUT: DataCM State[%d]\n    at HardwareAssertion.scala:145 assert(!eda_err, descStr)\n",
                 reg_state);	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :289:23
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:289:23
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:289:23
      end
      if (~reset & to_cnt[22]) begin	// src/main/scala/dongjiang/data/DataCM.scala:143:17, :289:23
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:289:23
          $error("Assertion failed: src/main/scala/dongjiang/data/DataCM.scala:289:23: TIMEOUT: DataCM State[%d]\n    at HardwareAssertion.scala:95 assert(assertCond, descStr)(s)\n",
                 reg_state);	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :289:23
        if (`STOP_COND_)	// src/main/scala/dongjiang/data/DataCM.scala:289:23
          $fatal;	// src/main/scala/dongjiang/data/DataCM.scala:289:23
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [1:0]      _GEN_28 = {1'h0, io_task_bits_dataVec_0};	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/dongjiang/data/DataCM.scala:179:87
  wire [1:0]      _GEN_29 = {1'h0, io_task_bits_dataVec_1};	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/dongjiang/data/DataCM.scala:179:87
  wire [1:0]      _GEN_30 = ~{io_clean_bits_dataVec_1, io_clean_bits_dataVec_0};	// src/main/scala/dongjiang/data/DataCM.scala:168:{52,75}
  always @(posedge clock) begin	// src/main/scala/dongjiang/data/DataCM.scala:64:7
    if (set) begin	// src/main/scala/dongjiang/data/DataCM.scala:283:27
      if (_set_T) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        reg_task_hnTxnID <= io_alloc_bits_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
        reg_wRBeat <= 2'h0;	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20
        reg_wSBeat <= 2'h0;	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20
        reg_dataVec_0 <= io_alloc_bits_dataVec_0;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
        reg_dataVec_1 <= io_alloc_bits_dataVec_1;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      end
      else begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (cutIdHit)	// src/main/scala/dongjiang/data/DataCM.scala:212:52
          reg_task_hnTxnID <= io_cutHnTxnID_bits_next;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
        else if (taskHit)	// src/main/scala/dongjiang/data/DataCM.scala:155:45
          reg_task_hnTxnID <= io_task_bits_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
        if (taskHit) begin	// src/main/scala/dongjiang/data/DataCM.scala:155:45
          reg_wRBeat <= io_task_bits_dataOp_read | io_task_bits_dataOp_repl ? 2'(_GEN_28 + _GEN_29) : 2'h0;	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20, :179:{25,51,87}
          reg_wSBeat <= io_task_bits_dataOp_send | io_task_bits_dataOp_repl ? 2'(_GEN_28 + _GEN_29) : 2'h0;	// <stdin>:952698:5, :953237:5, :953776:5, :954315:5, :954854:5, :955393:5, :955932:5, :956471:5, src/main/scala/dongjiang/data/DataCM.scala:92:20, :179:87, :192:{25,51,87}
        end
        else begin	// src/main/scala/dongjiang/data/DataCM.scala:155:45
          if (dsWriDBHit)	// src/main/scala/dongjiang/data/DataCM.scala:175:52
            reg_wRBeat <= 2'(reg_wRBeat - 2'h1);	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :182:33
          if (txDatHit)	// src/main/scala/dongjiang/data/DataCM.scala:188:54
            reg_wSBeat <= 2'(reg_wSBeat - 2'h1);	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :195:33
        end
        reg_dataVec_0 <= (~cleanHit | _GEN_30[0]) & reg_dataVec_0;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :164:47, :167:24, :168:{19,50,52,83}
        reg_dataVec_1 <= (~cleanHit | _GEN_30[1]) & reg_dataVec_1;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :96:22, :164:47, :167:24, :168:{19,50,52,83}
      end
      reg_opBeat <= next_opBeat;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :201:23, :202:19, :203:71
    end
    if (set & taskHit) begin	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :155:45, :283:27, :284:{13,19}
      reg_task_dataOp_send <= io_task_bits_dataOp_send;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_dataOp_save <= io_task_bits_dataOp_save;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_ds_bank <= io_task_bits_ds_bank;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_ds_idx <= io_task_bits_ds_idx;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_dataVec_0 <= io_task_bits_dataVec_0;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_dataVec_1 <= io_task_bits_dataVec_1;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_DBID <= io_task_bits_txDat_DBID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_CBusy <= io_task_bits_txDat_CBusy;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_DataSource <= io_task_bits_txDat_DataSource;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_Resp <= io_task_bits_txDat_Resp;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_RespErr <= io_task_bits_txDat_RespErr;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_Opcode <= io_task_bits_txDat_Opcode;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_HomeNID <= io_task_bits_txDat_HomeNID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_TxnID <= io_task_bits_txDat_TxnID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_SrcID <= io_task_bits_txDat_SrcID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_TgtID <= io_task_bits_txDat_TgtID;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
      reg_task_txDat_QoS <= io_task_bits_txDat_QoS;	// src/main/scala/dongjiang/data/DataCM.scala:92:20
    end
    if ((|reg_state) & to_cnt[22]) begin	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20, :289:23
    end
    else if (|reg_state)	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :92:20
      to_cnt <= 23'(to_cnt + 23'h1);	// src/main/scala/dongjiang/data/DataCM.scala:289:23
    else	// src/main/scala/dongjiang/data/DataCM.scala:50:25
      to_cnt <= 23'h0;	// src/main/scala/dongjiang/data/DataCM.scala:289:23
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin	// src/main/scala/dongjiang/data/DataCM.scala:64:7
    if (reset)	// src/main/scala/dongjiang/data/DataCM.scala:64:7
      reg_state <= 3'h0;	// <stdin>:952701:30, :953240:30, :953779:30, :954318:30, :954857:30, :955396:30, :955935:30, :956474:30, src/main/scala/dongjiang/data/DataCM.scala:92:20
    else if (set)	// src/main/scala/dongjiang/data/DataCM.scala:283:27
      reg_state <= next_state;	// src/main/scala/dongjiang/data/DataCM.scala:92:20, :221:21, :223:27
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/dongjiang/data/DataCM.scala:64:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/dongjiang/data/DataCM.scala:64:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/dongjiang/data/DataCM.scala:64:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/dongjiang/data/DataCM.scala:64:7
      if (reset)	// src/main/scala/dongjiang/data/DataCM.scala:64:7
        reg_state = 3'h0;	// <stdin>:952701:30, :953240:30, :953779:30, :954318:30, :954857:30, :955396:30, :955935:30, :956474:30, src/main/scala/dongjiang/data/DataCM.scala:92:20
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/dongjiang/data/DataCM.scala:64:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/dongjiang/data/DataCM.scala:64:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_alloc_ready = ~(|reg_state);	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :64:7, :92:20
  assign io_resp_valid = io_resp_valid_0;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :148:59
  assign io_resp_bits_hnTxnID = reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readForRepl = io_readForRepl_0;	// src/main/scala/dongjiang/data/DataCM.scala:53:25, :64:7
  assign io_readToDB_valid = io_readToDB_valid_0;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :121:45
  assign io_readToDB_bits_ds_bank = reg_task_ds_bank;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDB_bits_ds_idx = reg_task_ds_idx;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDB_bits_dcid = io_dcid;	// src/main/scala/dongjiang/data/DataCM.scala:64:7
  assign io_readToDB_bits_beatNum = reg_opBeat | ~reg_task_dataVec_0;	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20, :93:25
  assign io_readToDB_bits_critical = reg_opBeat;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDS_valid = io_readToDS_valid_0;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :128:45
  assign io_readToDS_bits_ds_bank = reg_task_ds_bank;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDS_bits_ds_idx = reg_task_ds_idx;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDS_bits_dcid = io_dcid;	// src/main/scala/dongjiang/data/DataCM.scala:64:7
  assign io_readToDS_bits_beatNum = reg_opBeat | ~reg_task_dataVec_0;	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20, :93:25
  assign io_readToDS_bits_critical = reg_opBeat;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_readToDS_bits_repl = io_readForRepl_0;	// src/main/scala/dongjiang/data/DataCM.scala:53:25, :64:7
  assign io_readToCHI_valid = io_readToCHI_valid_0;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :136:45
  assign io_readToCHI_bits_dcid = io_dcid;	// src/main/scala/dongjiang/data/DataCM.scala:64:7
  assign io_readToCHI_bits_beatNum = reg_opBeat | ~reg_task_dataVec_0;	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20, :93:25
  assign io_readToCHI_bits_critical = reg_opBeat;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_DataID = {_GEN, 1'h0};	// <stdin>:952696:5, :953235:5, :953774:5, :954313:5, :954852:5, :955391:5, :955930:5, :956469:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/dongjiang/data/DataCM.scala:64:7
  assign io_txDatBits_DBID = reg_task_txDat_DBID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_CBusy = reg_task_txDat_CBusy;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_DataSource = reg_task_txDat_DataSource;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_Resp = reg_task_txDat_Resp;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_RespErr = reg_task_txDat_RespErr;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_Opcode = reg_task_txDat_Opcode;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_HomeNID = reg_task_txDat_HomeNID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_TxnID = reg_task_txDat_TxnID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_SrcID = reg_task_txDat_SrcID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_TgtID = reg_task_txDat_TgtID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_txDatBits_QoS = reg_task_txDat_QoS;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
  assign io_state_valid = |reg_state;	// src/main/scala/dongjiang/data/DataCM.scala:50:25, :64:7, :92:20
  assign io_state_bits_hnTxnID = reg_task_hnTxnID;	// src/main/scala/dongjiang/data/DataCM.scala:64:7, :92:20
endmodule

